//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace NreKnowledgebase.SchemaV5 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nationalrail.co.uk/xml/incident")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://nationalrail.co.uk/xml/incident", IsNullable=false)]
    public partial class Incidents {
        
        private PtIncidentStructure[] ptIncidentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PtIncident")]
        public PtIncidentStructure[] PtIncident {
            get {
                return this.ptIncidentField;
            }
            set {
                this.ptIncidentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nationalrail.co.uk/xml/incident")]
    [System.Xml.Serialization.XmlRootAttribute("PtIncident", Namespace="http://nationalrail.co.uk/xml/incident", IsNullable=false)]
    public partial class PtIncidentStructure {
        
        private System.DateTime creationTimeField;
        
        private ChangeHistoryStructure changeHistoryField;
        
        private string participantRefField;
        
        private string incidentNumberField;
        
        private string versionField;
        
        private SourceStructure sourceField;
        
        private HalfOpenTimestampRangeStructure outerValidityPeriodField;
        
        private PtIncidentStructureValidityPeriod[] validityPeriodField;
        
        private bool plannedField;
        
        private string summaryField;
        
        private string descriptionField;
        
        private InfoLinkStructure[] infoLinksField;
        
        private AffectsStructure affectsField;
        
        private bool clearedIncidentField;
        
        private bool clearedIncidentFieldSpecified;
        
        private string incidentPriorityField;
        
        private string p0SummaryField;
        
        public PtIncidentStructure() {
            this.plannedField = false;
        }
        
        /// <remarks/>
        public System.DateTime CreationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
            }
        }
        
        /// <remarks/>
        public ChangeHistoryStructure ChangeHistory {
            get {
                return this.changeHistoryField;
            }
            set {
                this.changeHistoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string ParticipantRef {
            get {
                return this.participantRefField;
            }
            set {
                this.participantRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string IncidentNumber {
            get {
                return this.incidentNumberField;
            }
            set {
                this.incidentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public SourceStructure Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public HalfOpenTimestampRangeStructure OuterValidityPeriod {
            get {
                return this.outerValidityPeriodField;
            }
            set {
                this.outerValidityPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValidityPeriod")]
        public PtIncidentStructureValidityPeriod[] ValidityPeriod {
            get {
                return this.validityPeriodField;
            }
            set {
                this.validityPeriodField = value;
            }
        }
        
        /// <remarks/>
        public bool Planned {
            get {
                return this.plannedField;
            }
            set {
                this.plannedField = value;
            }
        }
        
        /// <remarks/>
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("InfoLink", IsNullable=false)]
        public InfoLinkStructure[] InfoLinks {
            get {
                return this.infoLinksField;
            }
            set {
                this.infoLinksField = value;
            }
        }
        
        /// <remarks/>
        public AffectsStructure Affects {
            get {
                return this.affectsField;
            }
            set {
                this.affectsField = value;
            }
        }
        
        /// <remarks/>
        public bool ClearedIncident {
            get {
                return this.clearedIncidentField;
            }
            set {
                this.clearedIncidentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearedIncidentSpecified {
            get {
                return this.clearedIncidentFieldSpecified;
            }
            set {
                this.clearedIncidentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string IncidentPriority {
            get {
                return this.incidentPriorityField;
            }
            set {
                this.incidentPriorityField = value;
            }
        }
        
        /// <remarks/>
        public string P0Summary {
            get {
                return this.p0SummaryField;
            }
            set {
                this.p0SummaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nationalrail.co.uk/xml/common")]
    public partial class ChangeHistoryStructure {
        
        private ChangeHistoryStructureChangedBy changedByField;
        
        private System.DateTime lastChangedDateField;
        
        /// <remarks/>
        public ChangeHistoryStructureChangedBy ChangedBy {
            get {
                return this.changedByField;
            }
            set {
                this.changedByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastChangedDate {
            get {
                return this.lastChangedDateField;
            }
            set {
                this.lastChangedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nationalrail.co.uk/xml/common")]
    public partial class ChangeHistoryStructureChangedBy {
        
        private string tocAffiliationField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tocAffiliation {
            get {
                return this.tocAffiliationField;
            }
            set {
                this.tocAffiliationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nationalrail.co.uk/xml/incident")]
    public partial class AffectedOperatorStructure {
        
        private string operatorRefField;
        
        private string operatorNameField;
        
        /// <remarks/>
        public string OperatorRef {
            get {
                return this.operatorRefField;
            }
            set {
                this.operatorRefField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nationalrail.co.uk/xml/incident")]
    public partial class AffectsStructure {
        
        private AffectedOperatorStructure[] operatorsField;
        
        private string routesAffectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AffectedOperator", IsNullable=false)]
        public AffectedOperatorStructure[] Operators {
            get {
                return this.operatorsField;
            }
            set {
                this.operatorsField = value;
            }
        }
        
        /// <remarks/>
        public string RoutesAffected {
            get {
                return this.routesAffectedField;
            }
            set {
                this.routesAffectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nationalrail.co.uk/xml/incident")]
    public partial class InfoLinkStructure {
        
        private string uriField;
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nationalrail.co.uk/xml/common")]
    public partial class HalfOpenTimestampRangeStructure {
        
        private System.DateTime startTimeField;
        
        private System.DateTime endTimeField;
        
        private bool endTimeFieldSpecified;
        
        /// <remarks/>
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndTimeSpecified {
            get {
                return this.endTimeFieldSpecified;
            }
            set {
                this.endTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nationalrail.co.uk/xml/incident")]
    public partial class SourceStructure {
        
        private string twitterHashtagField;
        
        /// <remarks/>
        public string TwitterHashtag {
            get {
                return this.twitterHashtagField;
            }
            set {
                this.twitterHashtagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nationalrail.co.uk/xml/incident")]
    public partial class PtIncidentStructureValidityPeriod : HalfOpenTimestampRangeStructure {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Xml.Serialization.XmlRootAttribute("BS7666Address", Namespace="http://www.govtalk.gov.uk/people/bs7666", IsNullable=false)]
    public partial class BSaddressStructure {
        
        private AONstructure sAONField;
        
        private AONstructure pAONField;
        
        private string streetDescriptionField;
        
        private string uniqueStreetReferenceNumberField;
        
        private string[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        private string postTownField;
        
        private string postCodeField;
        
        private string uniquePropertyReferenceNumberField;
        
        /// <remarks/>
        public AONstructure SAON {
            get {
                return this.sAONField;
            }
            set {
                this.sAONField = value;
            }
        }
        
        /// <remarks/>
        public AONstructure PAON {
            get {
                return this.pAONField;
            }
            set {
                this.pAONField = value;
            }
        }
        
        /// <remarks/>
        public string StreetDescription {
            get {
                return this.streetDescriptionField;
            }
            set {
                this.streetDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string UniqueStreetReferenceNumber {
            get {
                return this.uniqueStreetReferenceNumberField;
            }
            set {
                this.uniqueStreetReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdministrativeArea", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Locality", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Town", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        public string PostTown {
            get {
                return this.postTownField;
            }
            set {
                this.postTownField = value;
            }
        }
        
        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string UniquePropertyReferenceNumber {
            get {
                return this.uniquePropertyReferenceNumberField;
            }
            set {
                this.uniquePropertyReferenceNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class AONstructure {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("EndRange", typeof(AONrangeStructure))]
        [System.Xml.Serialization.XmlElementAttribute("StartRange", typeof(AONrangeStructure))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class AONrangeStructure {
        
        private string numberField;
        
        private string suffixField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        EndRange,
        
        /// <remarks/>
        StartRange,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        AdministrativeArea,
        
        /// <remarks/>
        Locality,
        
        /// <remarks/>
        Town,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    [System.Xml.Serialization.XmlRootAttribute("BS7666BLPU", Namespace="http://www.govtalk.gov.uk/people/bs7666", IsNullable=false)]
    public partial class BasicLandAndPropertyUnitStructure {
        
        private string uniquePropertyReferenceNumberField;
        
        private string custodianCodeField;
        
        private RepresentativePointCodeType representativePointCodeField;
        
        private LogicalStatusType logicalStatusField;
        
        private CoordinateStructure gridReferenceField;
        
        private System.DateTime bLPUentryDateField;
        
        private System.DateTime bLPUstartDateField;
        
        private System.DateTime bLPUendDateField;
        
        private bool bLPUendDateFieldSpecified;
        
        private System.DateTime bLPUlastUpdateDateField;
        
        private LandAndPropertyIdentifierStructure[] landAndPropertyIdentifierField;
        
        private ProvenanceStructure[] provenanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string UniquePropertyReferenceNumber {
            get {
                return this.uniquePropertyReferenceNumberField;
            }
            set {
                this.uniquePropertyReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CustodianCode {
            get {
                return this.custodianCodeField;
            }
            set {
                this.custodianCodeField = value;
            }
        }
        
        /// <remarks/>
        public RepresentativePointCodeType RepresentativePointCode {
            get {
                return this.representativePointCodeField;
            }
            set {
                this.representativePointCodeField = value;
            }
        }
        
        /// <remarks/>
        public LogicalStatusType LogicalStatus {
            get {
                return this.logicalStatusField;
            }
            set {
                this.logicalStatusField = value;
            }
        }
        
        /// <remarks/>
        public CoordinateStructure GridReference {
            get {
                return this.gridReferenceField;
            }
            set {
                this.gridReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BLPUentryDate {
            get {
                return this.bLPUentryDateField;
            }
            set {
                this.bLPUentryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BLPUstartDate {
            get {
                return this.bLPUstartDateField;
            }
            set {
                this.bLPUstartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BLPUendDate {
            get {
                return this.bLPUendDateField;
            }
            set {
                this.bLPUendDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BLPUendDateSpecified {
            get {
                return this.bLPUendDateFieldSpecified;
            }
            set {
                this.bLPUendDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BLPUlastUpdateDate {
            get {
                return this.bLPUlastUpdateDateField;
            }
            set {
                this.bLPUlastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LandAndPropertyIdentifier")]
        public LandAndPropertyIdentifierStructure[] LandAndPropertyIdentifier {
            get {
                return this.landAndPropertyIdentifierField;
            }
            set {
                this.landAndPropertyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Provenance")]
        public ProvenanceStructure[] Provenance {
            get {
                return this.provenanceField;
            }
            set {
                this.provenanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum RepresentativePointCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum LogicalStatusType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class CoordinateStructure {
        
        private ulong xField;
        
        private ulong yField;
        
        /// <remarks/>
        public ulong X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public ulong Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class LandAndPropertyIdentifierStructure {
        
        private AONstructure pAONField;
        
        private AONstructure sAONField;
        
        private string postTownField;
        
        private string postCodeField;
        
        private string levelField;
        
        private LogicalStatusType logicalStatusField;
        
        private bool officialAddressMarkerField;
        
        private bool officialAddressMarkerFieldSpecified;
        
        private System.DateTime lPIstartDateField;
        
        private System.DateTime lPIentryDateField;
        
        private System.DateTime lPIendDateField;
        
        private bool lPIendDateFieldSpecified;
        
        private System.DateTime lPIlastUpdateDateField;
        
        private object itemField;
        
        /// <remarks/>
        public AONstructure PAON {
            get {
                return this.pAONField;
            }
            set {
                this.pAONField = value;
            }
        }
        
        /// <remarks/>
        public AONstructure SAON {
            get {
                return this.sAONField;
            }
            set {
                this.sAONField = value;
            }
        }
        
        /// <remarks/>
        public string PostTown {
            get {
                return this.postTownField;
            }
            set {
                this.postTownField = value;
            }
        }
        
        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public LogicalStatusType LogicalStatus {
            get {
                return this.logicalStatusField;
            }
            set {
                this.logicalStatusField = value;
            }
        }
        
        /// <remarks/>
        public bool OfficialAddressMarker {
            get {
                return this.officialAddressMarkerField;
            }
            set {
                this.officialAddressMarkerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OfficialAddressMarkerSpecified {
            get {
                return this.officialAddressMarkerFieldSpecified;
            }
            set {
                this.officialAddressMarkerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LPIstartDate {
            get {
                return this.lPIstartDateField;
            }
            set {
                this.lPIstartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LPIentryDate {
            get {
                return this.lPIentryDateField;
            }
            set {
                this.lPIentryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LPIendDate {
            get {
                return this.lPIendDateField;
            }
            set {
                this.lPIendDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LPIendDateSpecified {
            get {
                return this.lPIendDateFieldSpecified;
            }
            set {
                this.lPIendDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LPIlastUpdateDate {
            get {
                return this.lPIlastUpdateDateField;
            }
            set {
                this.lPIlastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Street", typeof(StreetStructure))]
        [System.Xml.Serialization.XmlElementAttribute("USRN", typeof(string), DataType="integer")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class StreetStructure {
        
        private StreetReferenceTypeType streetReferenceTypeField;
        
        private CoordinateStructure startCoordinateField;
        
        private CoordinateStructure endCoordinateField;
        
        private decimal toleranceField;
        
        private string streetVersionNumberField;
        
        private System.DateTime streetEntryDateField;
        
        private System.DateTime streetClosureDateField;
        
        private bool streetClosureDateFieldSpecified;
        
        private string responsibleAuthorityField;
        
        private StreetDescriptiveIdentifierStructure descriptiveIdentifierField;
        
        private StreetDescriptiveIdentifierStructure streetAliasField;
        
        private StreetStructureStreetCrossReferences streetCrossReferencesField;
        
        private string usrnField;
        
        /// <remarks/>
        public StreetReferenceTypeType StreetReferenceType {
            get {
                return this.streetReferenceTypeField;
            }
            set {
                this.streetReferenceTypeField = value;
            }
        }
        
        /// <remarks/>
        public CoordinateStructure StartCoordinate {
            get {
                return this.startCoordinateField;
            }
            set {
                this.startCoordinateField = value;
            }
        }
        
        /// <remarks/>
        public CoordinateStructure EndCoordinate {
            get {
                return this.endCoordinateField;
            }
            set {
                this.endCoordinateField = value;
            }
        }
        
        /// <remarks/>
        public decimal Tolerance {
            get {
                return this.toleranceField;
            }
            set {
                this.toleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string StreetVersionNumber {
            get {
                return this.streetVersionNumberField;
            }
            set {
                this.streetVersionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime StreetEntryDate {
            get {
                return this.streetEntryDateField;
            }
            set {
                this.streetEntryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime StreetClosureDate {
            get {
                return this.streetClosureDateField;
            }
            set {
                this.streetClosureDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StreetClosureDateSpecified {
            get {
                return this.streetClosureDateFieldSpecified;
            }
            set {
                this.streetClosureDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ResponsibleAuthority {
            get {
                return this.responsibleAuthorityField;
            }
            set {
                this.responsibleAuthorityField = value;
            }
        }
        
        /// <remarks/>
        public StreetDescriptiveIdentifierStructure DescriptiveIdentifier {
            get {
                return this.descriptiveIdentifierField;
            }
            set {
                this.descriptiveIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public StreetDescriptiveIdentifierStructure StreetAlias {
            get {
                return this.streetAliasField;
            }
            set {
                this.streetAliasField = value;
            }
        }
        
        /// <remarks/>
        public StreetStructureStreetCrossReferences StreetCrossReferences {
            get {
                return this.streetCrossReferencesField;
            }
            set {
                this.streetCrossReferencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string usrn {
            get {
                return this.usrnField;
            }
            set {
                this.usrnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum StreetReferenceTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class StreetDescriptiveIdentifierStructure {
        
        private string streetDescriptionField;
        
        private string[] itemsField;
        
        private ItemsChoiceType2[] itemsElementNameField;
        
        /// <remarks/>
        public string StreetDescription {
            get {
                return this.streetDescriptionField;
            }
            set {
                this.streetDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdministrativeArea", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Locality", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Town", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666", IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
        
        /// <remarks/>
        AdministrativeArea,
        
        /// <remarks/>
        Locality,
        
        /// <remarks/>
        Town,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class StreetStructureStreetCrossReferences {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ElementaryStreetUnit", typeof(ElementaryStreetUnitStructure))]
        [System.Xml.Serialization.XmlElementAttribute("UniqueStreetReferenceNumbers", typeof(string), DataType="integer")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class ElementaryStreetUnitStructure {
        
        private string eSUidentityField;
        
        private string eSUversionField;
        
        private System.DateTime eSUentryDateField;
        
        private System.DateTime eSUclosureDateField;
        
        private bool eSUclosureDateFieldSpecified;
        
        private CoordinateStructure startCoordinateField;
        
        private CoordinateStructure endCoordinateField;
        
        private decimal toleranceField;
        
        private CoordinateStructure[] intermediateCoordField;
        
        /// <remarks/>
        public string ESUidentity {
            get {
                return this.eSUidentityField;
            }
            set {
                this.eSUidentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string ESUversion {
            get {
                return this.eSUversionField;
            }
            set {
                this.eSUversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ESUentryDate {
            get {
                return this.eSUentryDateField;
            }
            set {
                this.eSUentryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ESUclosureDate {
            get {
                return this.eSUclosureDateField;
            }
            set {
                this.eSUclosureDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESUclosureDateSpecified {
            get {
                return this.eSUclosureDateFieldSpecified;
            }
            set {
                this.eSUclosureDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CoordinateStructure StartCoordinate {
            get {
                return this.startCoordinateField;
            }
            set {
                this.startCoordinateField = value;
            }
        }
        
        /// <remarks/>
        public CoordinateStructure EndCoordinate {
            get {
                return this.endCoordinateField;
            }
            set {
                this.endCoordinateField = value;
            }
        }
        
        /// <remarks/>
        public decimal Tolerance {
            get {
                return this.toleranceField;
            }
            set {
                this.toleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IntermediateCoord")]
        public CoordinateStructure[] IntermediateCoord {
            get {
                return this.intermediateCoordField;
            }
            set {
                this.intermediateCoordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class ProvenanceStructure {
        
        private ProvenanceCodeType provenanceCodeField;
        
        private string annotationField;
        
        private System.DateTime provEntryDateField;
        
        private System.DateTime provStartDateField;
        
        private System.DateTime provEndDateField;
        
        private bool provEndDateFieldSpecified;
        
        private System.DateTime provLastUpdateDateField;
        
        private BLPUextentStructure bLPUextentField;
        
        /// <remarks/>
        public ProvenanceCodeType ProvenanceCode {
            get {
                return this.provenanceCodeField;
            }
            set {
                this.provenanceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Annotation {
            get {
                return this.annotationField;
            }
            set {
                this.annotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ProvEntryDate {
            get {
                return this.provEntryDateField;
            }
            set {
                this.provEntryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ProvStartDate {
            get {
                return this.provStartDateField;
            }
            set {
                this.provStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ProvEndDate {
            get {
                return this.provEndDateField;
            }
            set {
                this.provEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProvEndDateSpecified {
            get {
                return this.provEndDateFieldSpecified;
            }
            set {
                this.provEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ProvLastUpdateDate {
            get {
                return this.provLastUpdateDateField;
            }
            set {
                this.provLastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        public BLPUextentStructure BLPUextent {
            get {
                return this.bLPUextentField;
            }
            set {
                this.bLPUextentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum ProvenanceCodeType {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        O,
        
        /// <remarks/>
        U,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class BLPUextentStructure {
        
        private string sourceDescriptionField;
        
        private System.DateTime extentEntryDateField;
        
        private System.DateTime extentSourceDateField;
        
        private System.DateTime extentStartDateField;
        
        private System.DateTime extentEndDateField;
        
        private bool extentEndDateFieldSpecified;
        
        private System.DateTime extentLastUpdateDateField;
        
        private BLPUpolygonStructure[] extentDefinitionField;
        
        /// <remarks/>
        public string SourceDescription {
            get {
                return this.sourceDescriptionField;
            }
            set {
                this.sourceDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ExtentEntryDate {
            get {
                return this.extentEntryDateField;
            }
            set {
                this.extentEntryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ExtentSourceDate {
            get {
                return this.extentSourceDateField;
            }
            set {
                this.extentSourceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ExtentStartDate {
            get {
                return this.extentStartDateField;
            }
            set {
                this.extentStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ExtentEndDate {
            get {
                return this.extentEndDateField;
            }
            set {
                this.extentEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtentEndDateSpecified {
            get {
                return this.extentEndDateFieldSpecified;
            }
            set {
                this.extentEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ExtentLastUpdateDate {
            get {
                return this.extentLastUpdateDateField;
            }
            set {
                this.extentLastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExtentDefinition")]
        public BLPUpolygonStructure[] ExtentDefinition {
            get {
                return this.extentDefinitionField;
            }
            set {
                this.extentDefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public partial class BLPUpolygonStructure {
        
        private string polygonIDField;
        
        private BLPUpolygonStructurePolygonType polygonTypeField;
        
        private bool polygonTypeFieldSpecified;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string PolygonID {
            get {
                return this.polygonIDField;
            }
            set {
                this.polygonIDField = value;
            }
        }
        
        /// <remarks/>
        public BLPUpolygonStructurePolygonType PolygonType {
            get {
                return this.polygonTypeField;
            }
            set {
                this.polygonTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PolygonTypeSpecified {
            get {
                return this.polygonTypeFieldSpecified;
            }
            set {
                this.polygonTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExternalRef", typeof(ulong))]
        [System.Xml.Serialization.XmlElementAttribute("Vertices", typeof(CoordinateStructure))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/people/bs7666")]
    public enum BLPUpolygonStructurePolygonType {
        
        /// <remarks/>
        H,
    }
}
